package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
)

const (
	autoGenStart = "<!-- BEGIN:SUPPORTED_OPCODES_AUTOGENERATED -->"
	autoGenEnd   = "<!-- END:SUPPORTED_OPCODES_AUTOGENERATED -->"
)

var opcodeConstRegexp = regexp.MustCompile(`(?m)^\s*(OP_[A-Z0-9]+)\s*=\s*0x([0-9a-f]{2})\s*//\s*(\d+)\s*$`)

type opcodeDef struct {
	Name     string
	Value    int
	Hex      string
	Category string
}

func main() {
	checkOnly := flag.Bool("check", false, "check README only; fail if not in sync")
	write := flag.Bool("write", false, "rewrite README autogenerated opcode block")
	flag.Parse()

	if (*checkOnly && *write) || (!*checkOnly && !*write) {
		exitWithError(errors.New("exactly one of --check or --write must be set"))
	}

	repoRoot, err := os.Getwd()
	if err != nil {
		exitWithError(fmt.Errorf("get working directory: %w", err))
	}

	readmePath := filepath.Join(repoRoot, "README.md")
	opcodePath := filepath.Join(repoRoot, "pkg", "arkade", "opcode.go")

	opcodes, err := loadDocumentedOpcodes(opcodePath)
	if err != nil {
		exitWithError(err)
	}

	readmeRaw, err := os.ReadFile(readmePath)
	if err != nil {
		exitWithError(fmt.Errorf("read README: %w", err))
	}

	updatedReadme, changed, err := syncReadme(readmeRaw, opcodes)
	if err != nil {
		exitWithError(err)
	}

	if *checkOnly {
		if changed {
			exitWithError(errors.New(
				"README supported opcode block is out of sync with pkg/arkade/opcode.go. Run: go run ./cmd/readme-sync --write",
			))
		}
		fmt.Println("README supported opcode block is in sync.")
		return
	}

	if !changed {
		fmt.Println("README supported opcode block already up to date.")
		return
	}

	if err := os.WriteFile(readmePath, updatedReadme, 0o644); err != nil {
		exitWithError(fmt.Errorf("write README: %w", err))
	}

	fmt.Println("Updated README supported opcode block.")
}

func exitWithError(err error) {
	fmt.Fprintf(os.Stderr, "error: %v\n", err)
	os.Exit(1)
}

func syncReadme(readme []byte, opcodes []opcodeDef) ([]byte, bool, error) {
	generated := generateReadmeBlock(opcodes)

	text := string(readme)
	startIdx := strings.Index(text, autoGenStart)
	endIdx := strings.Index(text, autoGenEnd)
	if startIdx == -1 || endIdx == -1 || endIdx < startIdx {
		return nil, false, errors.New("README missing autogenerated supported-opcodes block markers; run --write after adding markers")
	}

	endIdx += len(autoGenEnd)
	currentBlock := text[startIdx:endIdx]
	if currentBlock == generated {
		return readme, false, nil
	}

	var buf bytes.Buffer
	buf.WriteString(text[:startIdx])
	buf.WriteString(generated)
	buf.WriteString(text[endIdx:])
	return buf.Bytes(), true, nil
}

func loadDocumentedOpcodes(opcodePath string) ([]opcodeDef, error) {
	opcodeRaw, err := os.ReadFile(opcodePath)
	if err != nil {
		return nil, fmt.Errorf("read opcode definitions: %w", err)
	}

	constants := opcodeConstRegexp.FindAllStringSubmatch(string(opcodeRaw), -1)
	if len(constants) == 0 {
		return nil, errors.New("no opcode constants found in pkg/arkade/opcode.go")
	}

	all := make([]opcodeDef, 0, len(constants))
	for _, match := range constants {
		name := match[1]
		hexVal, err := strconv.ParseInt(match[2], 16, 32)
		if err != nil {
			return nil, fmt.Errorf("parse hex for %s: %w", name, err)
		}
		decVal, err := strconv.Atoi(match[3])
		if err != nil {
			return nil, fmt.Errorf("parse decimal for %s: %w", name, err)
		}
		if int(hexVal) != decVal {
			return nil, fmt.Errorf("mismatched opcode value for %s: hex=%d dec=%d", name, hexVal, decVal)
		}

		category, ok := opcodeCategory(name)
		if !ok {
			continue
		}

		all = append(all, opcodeDef{
			Name:     name,
			Value:    decVal,
			Hex:      fmt.Sprintf("0x%02x", decVal),
			Category: category,
		})
	}

	sort.Slice(all, func(i, j int) bool {
		if all[i].Value == all[j].Value {
			return all[i].Name < all[j].Name
		}
		return all[i].Value < all[j].Value
	})

	return all, nil
}

func generateReadmeBlock(opcodes []opcodeDef) string {
	var b strings.Builder
	b.WriteString(autoGenStart)
	b.WriteString("\n")
	b.WriteString("> This table is auto-generated from `pkg/arkade/opcode.go` by `go run ./cmd/readme-sync --write`.\n\n")
	b.WriteString("| Word | Opcode | Hex | Category |\n")
	b.WriteString("|------|--------|-----|----------|\n")
	for _, op := range opcodes {
		b.WriteString(fmt.Sprintf("| %s | %d | %s | %s |\n", op.Name, op.Value, op.Hex, op.Category))
	}
	b.WriteString(autoGenEnd)
	return b.String()
}

func opcodeCategory(name string) (string, bool) {
	if strings.HasPrefix(name, "OP_INSPECTASSET") || strings.HasPrefix(name, "OP_INSPECTOUTASSET") || strings.HasPrefix(name, "OP_INSPECTINASSET") ||
		name == "OP_INSPECTNUMASSETGROUPS" || name == "OP_FINDASSETGROUPBYASSETID" {
		return "Asset Introspection", true
	}

	if name == "OP_INSPECTPACKET" || name == "OP_INSPECTINPUTPACKET" {
		return "Packet Introspection", true
	}

	if strings.HasPrefix(name, "OP_INSPECTINPUT") || name == "OP_PUSHCURRENTINPUTINDEX" {
		return "Transaction Introspection (Inputs)", true
	}

	if strings.HasPrefix(name, "OP_INSPECTOUTPUT") {
		return "Transaction Introspection (Outputs)", true
	}

	if name == "OP_INSPECTVERSION" || name == "OP_INSPECTLOCKTIME" || name == "OP_INSPECTNUMINPUTS" ||
		name == "OP_INSPECTNUMOUTPUTS" || name == "OP_TXWEIGHT" || name == "OP_TXID" {
		return "Transaction Introspection (Transaction)", true
	}

	if slices.Contains([]string{"OP_CAT", "OP_SUBSTR", "OP_LEFT", "OP_RIGHT"}, name) {
		return "Data Manipulation", true
	}
	if slices.Contains([]string{"OP_INVERT", "OP_AND", "OP_OR", "OP_XOR"}, name) {
		return "Bitwise Logic", true
	}
	if slices.Contains([]string{"OP_2MUL", "OP_2DIV", "OP_MUL", "OP_DIV", "OP_MOD", "OP_LSHIFT", "OP_RSHIFT", "OP_NUM2BIN", "OP_BIN2NUM"}, name) {
		return "Arithmetic", true
	}
	if slices.Contains([]string{"OP_CHECKSIGFROMSTACK", "OP_MERKLEBRANCHVERIFY"}, name) {
		return "Cryptography", true
	}
	if slices.Contains([]string{"OP_ECMULSCALARVERIFY", "OP_TWEAKVERIFY"}, name) {
		return "Elliptic Curve Operations", true
	}
	if slices.Contains([]string{"OP_SHA256INITIALIZE", "OP_SHA256UPDATE", "OP_SHA256FINALIZE"}, name) {
		return "SHA256 Streaming Operations", true
	}

	return "", false
}
