package main

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	require.True(t, ok)
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

func TestLoadDocumentedOpcodesIncludesKnownEntries(t *testing.T) {
	t.Parallel()
	root := repoRoot(t)
	opcodes, err := loadDocumentedOpcodes(filepath.Join(root, "pkg", "arkade", "opcode.go"))
	require.NoError(t, err)
	require.NotEmpty(t, opcodes)

	found := map[string]bool{}
	for _, op := range opcodes {
		found[op.Name] = true
	}

	require.True(t, found["OP_INSPECTINASSETLOOKUP"])
	require.True(t, found["OP_TXID"])
	require.True(t, found["OP_SHA256FINALIZE"])
}

func TestReadmeAutogeneratedBlockIsInSync(t *testing.T) {
	t.Parallel()
	root := repoRoot(t)
	readmePath := filepath.Join(root, "README.md")
	opcodePath := filepath.Join(root, "pkg", "arkade", "opcode.go")

	opcodes, err := loadDocumentedOpcodes(opcodePath)
	require.NoError(t, err)

	readme, err := os.ReadFile(readmePath)
	require.NoError(t, err)

	_, changed, err := syncReadme(readme, opcodes)
	require.NoError(t, err)
	require.False(t, changed, "README opcode block is stale; run: go run ./cmd/readme-sync --write")
}

func TestGenerateReadmeBlockContainsMarkers(t *testing.T) {
	t.Parallel()
	block := generateReadmeBlock([]opcodeDef{{Name: "OP_TXID", Value: 243, Hex: "0xf3", Category: "Transaction Introspection (Transaction)"}})
	require.True(t, strings.HasPrefix(block, autoGenStart))
	require.Contains(t, block, "| OP_TXID | 243 | 0xf3 | Transaction Introspection (Transaction) |")
	require.True(t, strings.HasSuffix(block, autoGenEnd))
}
