{
  description = "Nitro Enclave - reproducible build";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    flake-utils.url = "github:numtide/flake-utils";
    aws-nitro-util.url = "github:monzo/aws-nitro-util";
  };

  outputs = { self, nixpkgs, flake-utils, aws-nitro-util }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ] (system:
      let
        pkgs = import nixpkgs { inherit system; };
        eifPkgs = if system == "x86_64-linux" then pkgs
                  else import nixpkgs { system = "x86_64-linux"; };
        eifBuildGoModule = eifPkgs.buildGoModule.override { go = eifPkgs.go_1_26; };
        nitro = aws-nitro-util.lib.x86_64-linux;

        # Read build config generated by `enclave build` from enclave.yaml.
        # BUILD_CONFIG_PATH is set by the CLI; is set by the CLI as an absolute path.
        # Requires --impure flag (already set by the CLI).
        configPath = let p = builtins.getEnv "BUILD_CONFIG_PATH"; in
          if p != "" then p else "../.enclave/build-config.json";
        buildCfg = builtins.fromJSON (builtins.readFile configPath);
        appCfg = buildCfg.app;
        runtimeCfg = buildCfg.runtime;

        # Fall back to env vars for backwards compatibility.
        version = buildCfg.version;
        region = buildCfg.region;
        deployment = buildCfg.prefix;

        # Resolve user-supplied package names from enclave.yaml
        # (nix_build_inputs / nix_native_build_inputs) against nixpkgs.
        resolveInputs = names: map (n: eifPkgs.${n}) names;

        # Enclave supervisor — built from the runtime repo.
        # Handles attestation, secrets, PCR extension, reverse proxy with
        # signing middleware. The user's app is just a plain HTTP server.
        runtime = eifBuildGoModule {
          pname = "runtime";
          version = buildCfg.version;

          src = eifPkgs.fetchFromGitHub {
            owner = "ArkLabsHQ";
            repo = "introspector-enclave";
            rev = runtimeCfg.rev;
            hash = runtimeCfg.hash;
          };

          sourceRoot = "source/runtime";
          vendorHash = runtimeCfg.vendor_hash;
          subPackages = [ "cmd/runtime" ];
          env.CGO_ENABLED = "0";
          ldflags = [
            "-X" "github.com/ArkLabsHQ/introspector-enclave/runtime.Version=${version}"
          ];
          buildFlags = [ "-trimpath" ];
          tags = [ "netgo" ];
          doCheck = false;
        };

        # User's app — fetched from GitHub. No runtime dependency needed.
        upstream-app = eifBuildGoModule ({
          pname = appCfg.binary_name;
          version = buildCfg.version;

          src = eifPkgs.fetchFromGitHub {
            owner = appCfg.nix_owner;
            repo = appCfg.nix_repo;
            rev = appCfg.nix_rev;
            hash = appCfg.nix_hash;
          };

          vendorHash = if appCfg.nix_vendor_hash == "" then null else appCfg.nix_vendor_hash;
          proxyVendor = true;

          subPackages = appCfg.nix_sub_packages;
          env.CGO_ENABLED = "0";
          buildFlags = [ "-trimpath" ];
          tags = [ "netgo" ];
          doCheck = false;

          nativeBuildInputs = resolveInputs (appCfg.nix_native_build_inputs or []);
          buildInputs = resolveInputs (appCfg.nix_build_inputs or []);

          postInstall = ''
            # Rename whatever was built to the configured binary name.
            for f in $out/bin/*; do
              if [ "$(basename "$f")" != "${appCfg.binary_name}" ]; then
                mv "$f" "$out/bin/${appCfg.binary_name}"
              fi
            done
          '';
        } // (if (appCfg.nix_subdir or "") != "" then {
          sourceRoot = "source/${appCfg.nix_subdir}";
        } else {}));

        # Nitriding and viproxy are vendored into the runtime binary (see
        # runtime/nitriding/ and runtime/viproxy/), so no separate derivations
        # are needed here — the runtime /app/runtime is the whole enclave
        # userspace alongside the user's app.

        # Assemble the /app directory with all binaries and scripts.
        appDir = eifPkgs.runCommand "enclave-app" { } ''
          mkdir -p $out/app/data
          cp ${upstream-app}/bin/${appCfg.binary_name} $out/app/${appCfg.binary_name}
          cp ${runtime}/bin/runtime $out/app/runtime
        '';

        # Complete rootfs for the enclave.
        enclaveRootfs = eifPkgs.buildEnv {
          name = "enclave-rootfs";
          paths = [
            appDir
            eifPkgs.busybox    # provides /bin/sh and basic utils
            eifPkgs.cacert     # TLS CA certificates
          ];
          pathsToLink = [ "/" ];
        };

        # Secrets config JSON baked into the EIF for runtime discovery.
        secretsCfgJson = builtins.toJSON (buildCfg.secrets or []);

        # Environment variables for the enclave.
        # Standard vars + all app-specific vars from build-config.json.
        enclaveEnv = let
          appEnvLines = builtins.concatStringsSep "\n"
            (builtins.map (k: "${k}=${builtins.getAttr k appCfg.env}")
              (builtins.attrNames appCfg.env));
        in ''
          PATH=/app:/bin:/usr/bin
          SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
          AWS_REGION=${region}
          ENCLAVE_APP_NAME=${buildCfg.name}
          ENCLAVE_SECRETS_CONFIG=${secretsCfgJson}
          ENCLAVE_MIGRATION_COOLDOWN=${buildCfg.migration_cooldown or "0s"}
          ENCLAVE_PREVIOUS_PCR0=${buildCfg.previous_pcr0 or "genesis"}
          ENCLAVE_KMS_KEY_LOCKED=${if buildCfg.is_kms_key_locked or false then "true" else "false"}
          ENCLAVE_DEPLOYMENT=${deployment}
          ${appEnvLines}
        '';

        # Build EIF using monzo/aws-nitro-util (reproducible, no Docker).
        eif = nitro.buildEif {
          name = "${buildCfg.name}-enclave";
          inherit version;

          arch = "x86_64";
          kernel = nitro.blobs.x86_64.kernel;
          kernelConfig = nitro.blobs.x86_64.kernelConfig;
          nsmKo = nitro.blobs.x86_64.nsmKo;

          copyToRoot = enclaveRootfs;
          entrypoint = "/app/runtime";
          env = enclaveEnv;
        };

        # Vendor hash check — used by enclave setup to discover the correct hash.
        vendor-hash-check = eifBuildGoModule ({
          pname = "vendor-hash-check";
          version = buildCfg.version;
          src = eifPkgs.fetchFromGitHub {
            owner = appCfg.nix_owner;
            repo = appCfg.nix_repo;
            rev = appCfg.nix_rev;
            hash = appCfg.nix_hash;
          };
          vendorHash = "";
          proxyVendor = true;
          subPackages = appCfg.nix_sub_packages;
          env.CGO_ENABLED = "0";
          doCheck = false;

          nativeBuildInputs = resolveInputs (appCfg.nix_native_build_inputs or []);
          buildInputs = resolveInputs (appCfg.nix_build_inputs or []);
        } // (if (appCfg.nix_subdir or "") != "" then {
          sourceRoot = "source/${appCfg.nix_subdir}";
        } else {}));

      in
      {
        packages = {
          inherit upstream-app runtime eif vendor-hash-check;
          default = eif;
        };
      }
    );
}
